import type { Metadata } from "next";
import "./globals.css";
import { Titillium_Web, Amaranth } from "next/font/google";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { cn } from "@/lib/utils";

const titillium_Web = Titillium_Web({ weight: "400", subsets: ["latin"] });
export const amaranth = Amaranth({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(titillium_Web.className)}
      >
        <div className="relative max-w-7xl mx-auto px-2 py-2 md:px-6">
          {/* Navbar */}
          <Navbar />
          {/* Page Content */}
          <main className="pt-16">
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
